### DISCUSSION TITLE
modified pepa-linha-dark theme

### DISCUSSION THREAD

**Discussion by ichier** [vrana/adminer#1037] [Show and tell]
When i started using (the amazing piece of work) adminer i chose the pepa-linha-dark theme, with i loved the most - by far.
in oder to make it a work-horse (rather than a data-presentation one), i modified it to be more dense, show a lot more data.
so with recent adminer-updates i kept modifying it, and while reporting a php-warning just now, i thought i might share it. so here it is:
[adminer.pepa-linha-dark_ichier.zip](https://github.com/user-attachments/files/19737997/adminer.pepa-linha-dark_ichier.zip)

i can put it on github, if there's interest or it gets shared on the adminerwebsite.

**Comment by m-ristau** [comment]
Ahoi there, since i did what you describe here just yesterday, i can agree on your thoughts.
I felt also forced to increase the density immediately and could not hold myself from darkening it.
I wasnt putting as much efford into, also because i was there to work with and not on it.

Iam happy to see iam not alone with my demands and choices made.
I saw you put some time in the dropdowns, which i totally skipped.
Maybe we should share our steps on the line.

---
Feel free to get in touch and also check out my mess:
[filamentish - my interpretion of pepa-linha's work](https://github.com/m-ristau/adminer-filamentish)
_Take care!_ 👌

**Comment by vrana** [comment]
@ichier, I've linked the filamentish design from [adminer.org](https://www.adminer.org/en/#extras). Please let me know if you can maybe work together to come up with one design that suits you both or if you want me to link your design separately. If the latter then please put it somewhere on GitHub.

**Comment by ichier** [comment]
Hey there!
Seems like you put quite some more effort in there @m-ristau, having variables and such ;)
But since you also changed the colour-theme and i still like how calm the original feels, i'd like to keep my lil mods.
So i put up a repo: [adminer-pepa-linha-dark-ichier](https://github.com/ichier/adminer-pepa-linha-dark-ichier)
Feel free to take whatever you want, of course! I already stealt the checkmark from yours. Also if you see something really missing there, let me know.
And thanx for your work @vrana! (I stumbled over your rant about the php8-warnings the other day, and man!, finally, i don't feel so alone and anachronistic anymore...)

**Reply by vrana** [reply]
Linked from https://www.adminer.org/#extras, thanks. Can you rename `adminer.pepa-linha-dark_ichier.css` just to `adminer-dark.css` so that's it's simpler to use?

**Reply by ichier** [reply]
allright, just did that. also fixed the last bug, hehe.

**Comment by m-ristau** [comment]
Hey @ichier ,

since iam **guaranteed** honest if my sentance start by:
> "I wasnt putting as much efford..."

I wonder what happened and noticed that you probably grabbed an old Stylesheet from the Adminer Homepage and start cooking on a very old version!
```css
/* 
 * [######## YOU ########]
 * Dark Theme by Pepa Linha [http://webdream.cz]
 * @version 1.0.5
 * modified by Ichier v0.5
 *
 * [###### SOURCE #######]
 * Dark Theme by Pepa Linha [http://webdream.cz]
 * @version 2.0.1
 */
:root {
    /* Base colors */
    --color-white: #fff;
    --color-green: #5df1dc;
    --color-green-dark: #0d3a33;
    --color-orange: #ffb978;
    --color-blue: #8fc3f7;
    --color-blue-light: #c4d3f5;
    --color-purple: #a1a6e0;
    --color-purple-600: #797998;
    --color-purple-700: #4b4c68;
    --color-purple-800: #312f42;
    --color-purple-900: #2e2c3e;
    --color-purple-1000: #2a2838;
    --color-red: #e44747;
    --color-black: #000;
}
```
_Take a look [at this](https://raw.githubusercontent.com/pepa-linha/Adminer-Design-Dark/refs/heads/master/adminer.css).
Lets stay in touch so we can maybe just switch the variables and merge later!
I will try to stick only to the ones given.
Take care!_
