### ISSUE TITLE
Long running query blocks other tabs

### ISSUE THREAD

**Issue by W1zzardTPU** [vrana/adminer#1084]
**Adminer version:** 5.2.1-standalone
**Compiled:** docker image
**Driver:** MySQL
**Database version:** 8.4.3
**Plugins used:**

When a long running query is running in one tab, loading adminer in other tabs hangs until the other tab is finished

I vaguely remember this was fixed in the past by making a change to the session handling?

**Comment by vrana** [comment]
The Docker image uses `php -S` which is single-threaded.

Also, report bugs to the Docker image at https://github.com/TimWolla/docker-adminer.

**Comment by LorenzoRogai** [comment]
For any other reader. You can solve it like this using adminer:fastcgi alternative

docker-compose.yml

```
version: "3.9"

services:
  adminer:
    image: adminer:fastcgi
    restart: always

  web:
    image: nginx:alpine
    depends_on:
      - adminer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
```

nginx.conf

```
worker_processes auto;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream adminer-php {
        server adminer:9000;  # php-fpm in the adminer:fastcgi container
    }

    server {
        listen 80;
        root /var/www/html;
        index index.php;

        location / {
            try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass adminer-php;
        }
    }
}
```
