### ISSUE TITLE
Boolean rendering inconsistent between table view and SQL command results despite custom plugin

### ISSUE THREAD

**Issue by adarsh27april** [vrana/adminer#1100]
# Issue Description

Hi, I'm using Adminer via Docker, and I noticed inconsistent rendering of `boolean` column values in different parts of the UI.

When I browse a table using the Adminer UI, `boolean` fields are shown as `1` or empty (for true/false), which is a bit unclear. I tried to fix this by creating a small plugin that renders them as `"t"` or `"f"` — and that worked correctly in the table view.

However, when I run a SQL query manually in the SQL command section, the same `boolean` values appear again as `1` or empty. It seems that the plugin rendering is not applied in the SQL result output, unlike the table browsing view.

This creates confusion because the same data is rendered differently depending on how it's viewed.

# What I tried

I created a plugin like this:

```php
class AdminerBooleanText {
    function selectVal($val, $link, $field) {
        if ($field["type"] === "boolean") {
            return $val === "t" || $val === "1" ? "t" : "f";
        }
        return null;
    }
}
return new AdminerBooleanText();
```

This worked fine for table views, but had no effect on SQL command output.

Setup (in case it helps):
I'm running Adminer using Docker with the following plugin configuration:

```yaml
services:
  adminer:
    image: adminer:latest
    environment:
      - ADMINER_PLUGINS=json-column tables-filter boolean
    volumes:
      - ./adminer-plugins/boolean.php:/var/www/html/plugins/boolean.php
    ports:
      - 4444:8080
```

This is the table create sql:

```sql
CREATE TABLE "random" (
  "id" bigserial primary key,
  "istrue" boolean NOT NULL default true
)
```

# Expected behavior

It would be helpful if boolean values could be consistently rendered across both the table view and SQL command output, or if plugins like the one above could also hook into how SQL result rows are displayed.

<img width="559" alt="Image" src="https://github.com/user-attachments/assets/da8159ba-88c6-48d0-b869-a94576275da0" />\
<img width="270" alt="Image" src="https://github.com/user-attachments/assets/dca0060b-6df7-4ccd-9677-d788ae12ca9e" />
