### ISSUE TITLE
error applying csp plugin

### ISSUE THREAD

**Issue by GammaGames** [vrana/adminer#921]
**Adminer version:** 5.0.4-standalone (docker)
**Driver:** n/a
**Database version:** n/a

I've gone through the process of updating adminer to 5 (thanks so much for updating all those plugins!) but am still running into the following error:

```
<br />
<b>Fatal error</b>:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, int given in /var/www/html/plugins/plugin.php:34
Stack trace:
#0 /var/www/html/plugins/plugin.php(34): method_exists(1, 'csp')
#1 /var/www/html/plugins/plugin.php(162): AdminerPlugin-&gt;applyPlugin('csp', Array)
#2 /var/www/html/adminer.php(1341): AdminerPlugin-&gt;csp()
#3 /var/www/html/adminer.php(1307): Adminer\page_headers()
#4 /var/www/html/adminer.php(1379): Adminer\page_header('Login', '', NULL)
#5 /var/www/html/adminer.php(1380): Adminer\auth_error('')
#6 /var/www/html/index.php(52): require('/var/www/html/a...')
#7 {main}
  thrown in <b>/var/www/html/plugins/plugin.php</b> on line <b>34</b><br />
```

I've cleared cookies, opened in incognito, not sure what else I could do.

Here's my compose file, the container is running behind an nginx proxy:

```yaml
services:
  adminer:
    container_name: adminer
    image: adminer:5.0.4-standalone
    restart: unless-stopped
    volumes:
      - ./themes/production-theme.css:/var/www/html/server-host-name-adminer.css
      - ./plugins/database-hide.php:/var/www/html/plugins-enabled/database-hide.php
      - ./plugins/floatThead.php:/var/www/html/plugins/floatThead.php
      - ./plugins/AdminerCustomizeThemeBasedOnServer.php:/var/www/html/plugins/AdminerCustomizeThemeBasedOnServer.php
      - ./plugins/schema-default-to-public.php:/var/www/html/plugins/SchemaDefaultToPublic.php
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      ADMINER_PLUGINS: "json-column tables-filter floatThead AdminerCustomizeThemeBasedOnServer SchemaDefaultToPublic"
```
