### ISSUE TITLE
Allow custom themes + dark theme

### ISSUE THREAD

**Issue by GammaGames** [vrana/adminer#925]
I use the [AdminerCustomizeThemeBasedOnServer](https://github.com/mmokross/AdminerCustomizeThemeBasedOnServer) plugin to add custom css to the header depending on the server the user is connected to:

```css
@keyframes blinker {
    50% {
        opacity: 10%;
    }
}

a#h1:after, #content h2:nth-of-type(1)::after {
    content: ' DEV SERVER';
    color: red;
    animation: blinker 2s linear infinite;
    font-weight: bold;
}
```

If this plugin finds a matching css file adminer's dark theme no longer works, I think because of https://github.com/vrana/adminer/blob/9cfea02e19fe1bcb919d4eee4aa463e6db0c58f5/adminer/include/design.inc.php#L34

Could adminer be updated to allow extra custom css on top of the dark theme?
